### ISSUE TITLE
KeyError: 'module name can\'t contain "."'

### ISSUE THREAD

**Issue by bolin12** [jayleicn/animeGAN#4]
The classes in module.py contains some nn.Module layers whose names contains some'.' in it, so I got error messages like the title, so how could I play it??

**Comment by athulvingt** [comment]
Yeah I had the same Issue. How do we fix it?

**Comment by Reekomer** [comment]
This comes from this change: https://github.com/pytorch/vision/pull/474

**Comment by zsheill7** [comment]
install torch==0.3.1 and torchvision==0.2.1
